### ISSUE TITLE
Websocket close after login

### ISSUE THREAD

**Issue by sushrutp** [nathanielgraham/Mojo-Poker#1]
Hello Sir,
After login web socket is closing.
script modification is done with valid username and password and bookmark provided for same. 

```
    $tx->send('["login", { "username": "test" , "password": "test" }]');
 
 # $tx->send('["login_book", {"bookmark":"dc17c0317495691235faf2ba1063278f08e2a524"}]');
```
Script output

```
perl wsshell.pl

server: ["login_res",{"block":{},"level":2,"remote_address":"127.0.0.1","handle":"test","last_visit":1558971007,"username":"test","birthday":null,"bookmark":"8bc55bb6f39c7fc446dccac859e5e2749821ba80","login_id":24,"invested":{"1":2000},"success":1,"chips":{"1":2000},"user_id":2,"email":null,"ring_play":{}}]

WebSocket closed with code 1005.
WebSocket closed with code 1005.

```

Getting no clue about the issue can you help.

**Comment by nathanielgraham** [comment]
Ah, put the "guest_login" line back and it should work, that is:  

```
   $tx->send('["guest_login"]'); #required
   $tx->send('["login", { "username": "test" , "password": "test" }]');
```
The server forces you to first login as a guest and only then upgrade to a registered user. 
I did it that way so unregistered users could observe games as a guest. 

Let me know if that worked so I can close the issue.

**Comment by sushrutp** [comment]
Thank you so much for your reply. 
I just figured out the same but thought kind of workaround and might need proper fix.

But ok now we can close the issue thank you Sir for Repsonse
